version: '3.8'
services:
  php:
    container_name: app_php
    image: yiisoftware/yii2-php:8.1-apache
    volumes:
      - ~/.composer-docker/cache:/root/.composer/cache:delegated
      - ./:/app
    ports:
      - '8000:80'
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: challenge

  mysql:
    container_name: app_db
    image: mysql:latest
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    restart: always
    volumes:
      - yii-mysql-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_DATABASE: challenge
      TZ: Europe/Warsaw

  phpmyadmin:
    container_name: app_pma
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - '8888:80'
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=mysql
    depends_on:
      - mysql

volumes:
  yii-mysql-data: